# Generated by Django 4.0.1 on 2022-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_bot',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='discord_bot',
            name='date',
            field=models.DateField(),
        ),
    ]
