# Generated by Django 4.0.1 on 2022-01-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0002_discord_bot_url_alter_discord_bot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_bot',
            name='image',
            field=models.ImageField(default='C:/Users/constantion/Downloads/Telegram Desktop/photo_2022-01-13_08-56-10.jpg', upload_to='discord_bot/images'),
        ),
    ]
