# Generated by Django 4.0.1 on 2022-01-22 03:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0003_discord_bot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_bot',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[900, 1200], upload_to='discord_bot/images'),
        ),
    ]
