# Generated by Django 4.0.1 on 2022-01-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0004_alter_discord_bot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_bot',
            name='image',
            field=models.ImageField(default='C:/Users/constantion/Downloads/Telegram Desktop/photo_2022-01-13_08-56-10.jpg', upload_to='discord_bot/images'),
        ),
    ]
