# Generated by Django 4.0.1 on 2022-01-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0005_alter_discord_bot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_bot',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
